version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: 'true'
    ports:
      - "8080:8080"
